### PR TITLE
To-Do List code review

### PR DESCRIPTION
**Pull request by ritikarawat220**
### Add To-Do List files for Peer Feedback 🙌

### CODE REVIEW

**Comment by sawmon71293** [comment]
Hi @ritikarawat220 ,
Status Approved :  👏 👏 👏 


giphy


Highlights:
- [x] followed JavaScript practices
- [x] applied the DRY, KISS, and YAGNI rules. 
- [x] used HTML and CSS best practices.

Good job implementing the requirements 👍 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Comment by ritikarawat220** [comment]
@sawmon71293 🙌

**Review by AbdusSattar-70 — COMMENTED** [review]
### Approved 👏
Hi @ritikarawat220,👋,
Well done implementing the awesome project👏

**Highlights** 🚀 ✔️ ✔️

- [ ] The repo looks professional.✔️
- [ ] GitHub flow best practices have been followed✔️
- [ ] You have descriptive PR✔️Added a new JavaScript file and import it as a module
- [ ] Created a new JavaScript file for the new functionality.
- [ ]  Implemented a function for adding a new task
- [ ] Implemented a function for deleting a task
- [ ] Implemented a function for editing task descriptions.
- [ ] All changes to the To-Do List had been saved in local storage.


## Your project is complete! There is nothing else to say other than... it's time to merge it.

ClappingCongratsGIF


## Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @abdussattar-70 in your question so I can receive the notification.

**Comment by ritikarawat220** [comment]
@AbdusSattar-70

**Pull request merged**
